name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'plgames/**'
      - 'build.sh'
      - 'docker-compose.*.yml'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: ${{ github.repository }}-backend
  IMAGE_NAME_FRONTEND: ${{ github.repository }}-frontend

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        working-directory: ./plgames
        run: |
          export NODE_OPTIONS="--max-old-space-size=6144"
          yarn install --mode=skip-build

      - name: Generate Prisma client
        working-directory: ./plgames
        run: |
          yarn workspace @affine/server exec prisma generate || true

      - name: Build templates
        working-directory: ./plgames
        run: |
          yarn workspace @affine/templates build

      - name: Build backend (@affine/reader)
        working-directory: ./plgames
        run: |
          export NODE_OPTIONS="--max-old-space-size=6144"
          yarn workspace @affine/reader build

      - name: Build backend (@affine/server)
        working-directory: ./plgames
        run: |
          export NODE_OPTIONS="--max-old-space-size=6144"
          yarn workspace @affine/server build

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./plgames
          file: ./plgames/Dockerfile.simple
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize Git in plgames
        run: |
          cd plgames
          git init
          git add -A
          git commit -m "Build" || true

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        working-directory: ./plgames
        run: |
          export NODE_OPTIONS="--max-old-space-size=6144"
          yarn install --mode=skip-build

      - name: Build templates
        working-directory: ./plgames
        run: |
          yarn workspace @affine/templates build

      - name: Build frontend (@affine/web)
        working-directory: ./plgames
        run: |
          export NODE_OPTIONS="--max-old-space-size=6144"
          yarn plgames build -p @affine/web

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./plgames
          file: ./plgames/packages/frontend/apps/web/Dockerfile.simple
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
